### ISSUE TITLE
Konami code

### ISSUE THREAD

**Issue by Miljar** [PHP-WVL/content.php-wvl.be#2]
Als de konami-code ingetypt wordt, zou er iets moeten gebeuren met de code. Gelijk het logo dat wegrolt ofzo :smile_cat:

**Comment by jnstr** [comment]
Als de konami-code ingetypt wordt, zou het logo wegrollen en het logo van .net in de plaats komen, zou in de tekst iedere vermelding van PHP vervangen worden door .NET en zou het achtergrondkleur aangepast worden naar het kleur van .net (dat lelijke paars).
Of ga ik er weer over? :)

**Comment by coudenysj** [comment]
@Miljar +1
@jnstr-io -1

**Comment by jnstr** [comment]
Logo dat wegrolt was wat moeilijk te animeren (door margin:auto en dan gewoon een margin in te stellen, was er geen animatie). Heb er dan maar een bounce-effect van gemaakt. Goed zo?

**Comment by Miljar** [comment]
Spijtig dat het niet kan rollen, maar tis ook goed :+1:

**Comment by coudenysj** [comment]
Merci @jnstr-io !
